### ISSUE TITLE
Unable to access

### ISSUE THREAD

**Issue by N3EOP** [Zebraslive/Mass-Anime-Downloader#2]
Trial key bugged; the key given in the Free Trial Key `window:

`tria2_lcOdG#e5_(kf_anczsHz_X__34H1fz`

Buying a key doesn't work either, due to a misconfiguration in the merchant portal.

**Comment by Zebraslive** [comment]
@N3EOP Sorry this downloader isn't working right now. I will need to make another one that works for a different site other than 9anime.
