### ISSUE TITLE
stuck on login screen

### ISSUE THREAD

**Issue by slepeytime** [Zebraslive/Mass-Anime-Downloader#5]
i'm stuck on loading screen after logging with key access
![image](https://user-images.githubusercontent.com/114986115/193771989-b1537157-ccf5-49ce-839a-966bc22b8498.png)

**Comment by Zebraslive** [comment]
I will update it later today and will let you know when it's fixed.

Thanks for reporting this.

**Comment by Zebraslive** [comment]
@slepeytime Updated to new version. Re download from payhip page.

if you can't get the file from payhip, download from here https://www.sendbig.com/view-files/?Id=a17b7242-a012-4593-2dd7-bf96c4ab977b using your license key as the password.
